### ISSUE TITLE
Python版インストールスクリプトの改善案

### ISSUE THREAD

**Issue by ryo-san470** [ryo-san470/dotfiles#10]
現在インストールスクリプトをPythonで書いてあるがこれを様々な意味で修正したい.
## ロジック

おおまかにコマンドとしてはdownload, deploy, initの３つがある.
### download

このリポジトリをダウンロードする.基本的に `curl -sL http://dot.jtwp470.net | python` のような感じでワンライナーでインストールしたいので必要となるリポジトリを丸ごとダウンロードしたい.具体的には

``` bash
$ git clone https://github.com/jtwp470/dotfiles ~/.dotconfig/dotfiles
```

のようなコマンドが動く.
### deploy

デプロイコマンドでは基本的にリンクの張り替え等を行う.リポジトリ内の.で始まるファイルたちをホームディレクトリにリンクする.
### init

イニシャライズする必要があればここで行う.例えば `git submodule` などはここで行う.
## 実装方針
- Python標準ライブラリのみで構成する.
- Python 2.6 - 3.5 で動作することを保証する.
- WindowsでもPythonがあれば動くようにしてみたい.
- 表示が寂しいのでもう少しきちんと表示機能を付ける.

**Comment by jtwp470** [comment]
あとやるべきこと.

+ [ ] 各Pythonのバージョンで動作することを確認する
    + [ ] Python 2.6 
    + [ ] Python 2.7
    + [ ] Python 3.3
    + [ ] Python 3.4
    + [ ] Python 3.5
    + [ ] Python nightly
+ [ ] 表示を綺麗にする

**Comment by jtwp470** [comment]
Windows 10でもMSYSシェル上で動作することが確認できた.

**Comment by jtwp470** [comment]
ただし oh-my-zsh のインストールに失敗するみたいで一度停止した.
