### ISSUE TITLE
oh-my-zshの依存をなくす

### ISSUE THREAD

**Issue by ryo-san470** [ryo-san470/dotfiles#9]
依存をなくさないと結構辛い.

**Comment by jtwp470** [comment]
zplug を実際に入れてみた. 入れてみたことに起因して少し困ったことがおきているので解決法等を探る

* 新しく tmux の buffer を作ったときに なまえが自動的に which になる. 
* enhancd とかが動かない
* peco を zplug 経由でインストールできない?

**Comment by jtwp470** [comment]
zplug 経由で peco は入るみたいです．

**Comment by ryo-san470** [comment]
zplugに完全に移行を果たした 👍
